---
title: "DMS stub analysis sheet - plotting"
output: html_notebook
---


```{r}
library(ggplot2)
library(readr)
library(dplyr)
library(tidyr)
library(bio3d)

source("functions/dms_analysis_utilities.R")
```

```{r}
# Enrich2 score files
scores_file = "../data/scores/main_identifiers_scores.tsv"

variantscore_colnames <- c("hgvs", "SE_dms_1", "epsilon_dms_1", "score_dms_1", "SE_dms_2", "epsilon_dms_2", "score_dms_2", "SE_dms_3", "epsilon_dms_3", "score_dms_3", "SE_dms_4", "epsilon_dms_4", "score_dms_4", "SE_dms_5", "epsilon_dms_5", "score_dms_5")

variantscore_coltypes <- c("character", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric")

scores <- read_delim(scores_file, col_names = variantscore_colnames, skip=3)
scores <- process_hgvs_df(scores)

scores$is.wt = scores$mutation_type == "S"

# Write the dataframe to a csv
write.csv(scores, "../data/scores.csv", row.names = FALSE)
```

Load the WT sequence
```{r}
wt_fasta = "../data/sequences/WT_sequence.fasta"

con=file(wt_fasta,open="r")
wt = readLines(con)[2]
close(con)
```

Plot the fitness effect distributions
```{r}
ggplot(scores %>% filter(mutation_type != "X")) +
  geom_density(aes(x = score_dms_1, color=mutation_type), bw = "nrd", kernel='gaussian', linewidth=1) +
  xlab("Enrich2 score (dms_1)") + 
  ylab("Density") + 
  geom_vline(xintercept = 0, linetype="dotted") +
  theme_classic() + 
  scale_color_manual(values=variant_colorscheme) +
  labs(color = "Mutation type")

ggplot(scores %>% filter(mutation_type != "X")) +
  geom_density(aes(x = score_dms_2, color=mutation_type), bw = "nrd", kernel='gaussian', linewidth=1) +
  xlab("Enrich2 score (dms_2)") + 
  ylab("Density") + 
  geom_vline(xintercept = 0, linetype="dotted") +
  theme_classic() + 
  scale_color_manual(values=variant_colorscheme) +
  labs(color = "Mutation type")

ggplot(scores %>% filter(mutation_type != "X")) +
  geom_density(aes(x = score_dms_3, color=mutation_type), bw = "nrd", kernel='gaussian', linewidth=1) +
  xlab("Enrich2 score (dms_3)") + 
  ylab("Density") + 
  geom_vline(xintercept = 0, linetype="dotted") +
  theme_classic() + 
  scale_color_manual(values=variant_colorscheme) +
  labs(color = "Mutation type")

ggplot(scores %>% filter(mutation_type != "X")) +
  geom_density(aes(x = score_dms_4, color=mutation_type), bw = "nrd", kernel='gaussian', linewidth=1) +
  xlab("Enrich2 score (dms_4)") + 
  ylab("Density") + 
  geom_vline(xintercept = 0, linetype="dotted") +
  theme_classic() + 
  scale_color_manual(values=variant_colorscheme) +
  labs(color = "Mutation type")

ggplot(scores %>% filter(mutation_type != "X")) +
  geom_density(aes(x = score_dms_5, color=mutation_type), bw = "nrd", kernel='gaussian', linewidth=1) +
  xlab("Enrich2 score (dms_5)") + 
  ylab("Density") + 
  geom_vline(xintercept = 0, linetype="dotted") +
  theme_classic() + 
  scale_color_manual(values=variant_colorscheme) +
  labs(color = "Mutation type")
```

Create heatmaps of the scores
```{r}
print_heatmap(scores, score_dms_5, wt, scale = TRUE, invert_scale = TRUE, output_file = "../results/plots/heatmaps/heatmap_dms_5.pdf")

print_heatmap(scores, score_dms_3, wt, scale = TRUE, invert_scale = TRUE, output_file = "../results/plots/heatmaps/heatmap_dms_3.pdf")

print_heatmap(scores, score_dms_4, wt, scale = TRUE, invert_scale = TRUE, output_file = "../results/plots/heatmaps/heatmap_dms_4.pdf")

print_heatmap(scores, score_dms_1, wt, scale = TRUE, invert_scale = FALSE, output_file = "../results/plots/heatmaps/heatmap_dms_1.pdf")

print_heatmap(scores, score_dms_2, wt, scale = TRUE, invert_scale = FALSE, output_file = "../results/plots/heatmaps/heatmap_dms_2.pdf")

```

Plot the average scores
```{r}
avg_scores <- scores %>% 
  group_by(pos) %>%
  summarise(avg_dms_1 = mean(score_dms_1, na.rm=TRUE),
            avg_dms_2 = mean(score_dms_2, na.rm=TRUE),
            avg_dms_3 = mean(score_dms_3, na.rm=TRUE),
            avg_dms_4 = mean(score_dms_4, na.rm=TRUE),
            avg_dms_5 = mean(score_dms_5, na.rm=TRUE))

ggplot(avg_scores) +
  geom_density(aes(x = avg_dms_1), bw = "nrd", kernel='gaussian', linewidth=1) +
  xlab("Average Enrich2 score at position (dms_1)") + 
  ylab("Density") + 
  geom_vline(xintercept = 0, linetype="dotted") +
  theme_classic() + 
  scale_color_manual(values=variant_colorscheme)

ggplot(avg_scores) +
  geom_density(aes(x = avg_dms_2), bw = "nrd", kernel='gaussian', linewidth=1) +
  xlab("Average Enrich2 score at position (dms_2)") + 
  ylab("Density") + 
  geom_vline(xintercept = 0, linetype="dotted") +
  theme_classic() + 
  scale_color_manual(values=variant_colorscheme)

ggplot(avg_scores) +
  geom_density(aes(x = avg_dms_3), bw = "nrd", kernel='gaussian', linewidth=1) +
  xlab("Average Enrich2 score at position (dms_3)") + 
  ylab("Density") + 
  geom_vline(xintercept = 0, linetype="dotted") +
  theme_classic() + 
  scale_color_manual(values=variant_colorscheme)

ggplot(avg_scores) +
  geom_density(aes(x = avg_dms_4), bw = "nrd", kernel='gaussian', linewidth=1) +
  xlab("Average Enrich2 score at position (dms_4)") + 
  ylab("Density") + 
  geom_vline(xintercept = 0, linetype="dotted") +
  theme_classic() + 
  scale_color_manual(values=variant_colorscheme)

ggplot(avg_scores) +
  geom_density(aes(x = avg_dms_5), bw = "nrd", kernel='gaussian', linewidth=1) +
  xlab("Average Enrich2 score at position (dms_5)") + 
  ylab("Density") + 
  geom_vline(xintercept = 0, linetype="dotted") +
  theme_classic() + 
  scale_color_manual(values=variant_colorscheme)
```

Map the scores onto structures
```{r}
pdb_example1 <- read.pdb("../data/structures/example1.pdb")
pdb_example2 <- read.pdb("../data/structures/example2.pdb")

x = map_scores_pdb(pdb_example1, avg_scores, "avg_dms_1")
write.pdb(x, file="../results/structures/example1_dms_1.pdb")
x = map_scores_pdb(pdb_example1, avg_scores, "avg_dms_2")
write.pdb(x, file="../results/structures/example1_dms_2.pdb")
x = map_scores_pdb(pdb_example1, avg_scores, "avg_dms_3")
write.pdb(x, file="../results/structures/example1_dms_3.pdb")
x = map_scores_pdb(pdb_example1, avg_scores, "avg_dms_4")
write.pdb(x, file="../results/structures/example1_dms_4.pdb")
x = map_scores_pdb(pdb_example1, avg_scores, "avg_dms_5")
write.pdb(x, file="../results/structures/example1_dms_5.pdb")

x = map_scores_pdb(pdb_example2, avg_scores, "avg_dms_1")
write.pdb(x, file="../results/structures/example2_dms_1.pdb")
x = map_scores_pdb(pdb_example2, avg_scores, "avg_dms_2")
write.pdb(x, file="../results/structures/example2_dms_2.pdb")
x = map_scores_pdb(pdb_example2, avg_scores, "avg_dms_3")
write.pdb(x, file="../results/structures/example2_dms_3.pdb")
x = map_scores_pdb(pdb_example2, avg_scores, "avg_dms_4")
write.pdb(x, file="../results/structures/example2_dms_4.pdb")
x = map_scores_pdb(pdb_example2, avg_scores, "avg_dms_5")
write.pdb(x, file="../results/structures/example2_dms_5.pdb")
```